include: 'https://gitlab.e.foundation/e/os/build_module/raw/master/.gitlab-ci.yml'

variables:
  REPO_BRANCH: eelo-0.2
  REPO_DIRECTORY: EELO_0_2
  REPO_URL: https://gitlab.e.foundation/e/os/android.git
  PROJECT_PATH: packages/apps/Settings
